// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOc676BKxZ_MGGo4RR0iKpnrdJyLO3zfI',
    appId: '1:616670415620:web:f07cbcfaeccd867ce15e51',
    messagingSenderId: '616670415620',
    projectId: 'todo-app-88742',
    authDomain: 'todo-app-88742.firebaseapp.com',
    storageBucket: 'todo-app-88742.firebasestorage.app',
    measurementId: 'G-NT93T7GFY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEccRVwstOW9bf8ugkLe7lrwGS5YDQ2SQ',
    appId: '1:616670415620:android:079aec6b2b951f78e15e51',
    messagingSenderId: '616670415620',
    projectId: 'todo-app-88742',
    storageBucket: 'todo-app-88742.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAE54O4kur1GqDdXxaKoJxE8IRTyTFnDM',
    appId: '1:616670415620:ios:46d0e20a191450d8e15e51',
    messagingSenderId: '616670415620',
    projectId: 'todo-app-88742',
    storageBucket: 'todo-app-88742.firebasestorage.app',
    iosBundleId: 'com.example.mytodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAE54O4kur1GqDdXxaKoJxE8IRTyTFnDM',
    appId: '1:616670415620:ios:46d0e20a191450d8e15e51',
    messagingSenderId: '616670415620',
    projectId: 'todo-app-88742',
    storageBucket: 'todo-app-88742.firebasestorage.app',
    iosBundleId: 'com.example.mytodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOc676BKxZ_MGGo4RR0iKpnrdJyLO3zfI',
    appId: '1:616670415620:web:28982cce40a64c34e15e51',
    messagingSenderId: '616670415620',
    projectId: 'todo-app-88742',
    authDomain: 'todo-app-88742.firebaseapp.com',
    storageBucket: 'todo-app-88742.firebasestorage.app',
    measurementId: 'G-4WC7RGMLX4',
  );

}